// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualHealthProject.Data;

#nullable disable

namespace VirtualHealthProject.Migrations
{
    [DbContext(typeof(VirtualHealthDbContext))]
    [Migration("20241019102359_sssvvv")]
    partial class sssvvv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "04972214-ed08-4594-9db5-73c50192309c",
                            ConcurrencyStamp = "04972214-ed08-4594-9db5-73c50192309c",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "18ebd57b-2075-4ceb-bd1a-e888697dffed",
                            ConcurrencyStamp = "18ebd57b-2075-4ceb-bd1a-e888697dffed",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "38d828e6-c344-4ec0-b295-3000f6d5ea06",
                            ConcurrencyStamp = "38d828e6-c344-4ec0-b295-3000f6d5ea06",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "9fa367bc-0217-4f68-b173-57af2db76cde",
                            ConcurrencyStamp = "9fa367bc-0217-4f68-b173-57af2db76cde",
                            Name = "Pharmacist",
                            NormalizedName = "PHARMACIST"
                        },
                        new
                        {
                            Id = "33e37ac0-d18d-49fa-8737-27a50d419f9a",
                            ConcurrencyStamp = "33e37ac0-d18d-49fa-8737-27a50d419f9a",
                            Name = "WardAdmin",
                            NormalizedName = "WARDADMIN"
                        },
                        new
                        {
                            Id = "a5395c94-33d2-45f0-a65d-024ff1e18291",
                            ConcurrencyStamp = "a5395c94-33d2-45f0-a65d-024ff1e18291",
                            Name = "ScriptManager",
                            NormalizedName = "SCRIPTMANAGER"
                        },
                        new
                        {
                            Id = "bd81ab2b-1df6-4b0e-938b-aa55f1ba5188",
                            ConcurrencyStamp = "bd81ab2b-1df6-4b0e-938b-aa55f1ba5188",
                            Name = "StockManager",
                            NormalizedName = "STOCKMANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7f270bed-70c3-46c2-bd83-c47b73eb7e2d",
                            RoleId = "04972214-ed08-4594-9db5-73c50192309c"
                        },
                        new
                        {
                            UserId = "7f270bed-70c3-46c2-bd83-c47b73eb7e2d",
                            RoleId = "33e37ac0-d18d-49fa-8737-27a50d419f9a"
                        },
                        new
                        {
                            UserId = "15a39159-9060-4425-8c3e-ba218c4ca37d",
                            RoleId = "9fa367bc-0217-4f68-b173-57af2db76cde"
                        },
                        new
                        {
                            UserId = "a2f48359-0469-43b0-8654-f61b9d1ab286",
                            RoleId = "bd81ab2b-1df6-4b0e-938b-aa55f1ba5188"
                        },
                        new
                        {
                            UserId = "9668a0c8-1c05-4240-b413-18b4c4bf1873",
                            RoleId = "38d828e6-c344-4ec0-b295-3000f6d5ea06"
                        },
                        new
                        {
                            UserId = "854428da-d335-45ef-a793-dced73bbff77",
                            RoleId = "a5395c94-33d2-45f0-a65d-024ff1e18291"
                        },
                        new
                        {
                            UserId = "c4e8abc4-dbbf-406d-8031-20509b79c1a4",
                            RoleId = "18ebd57b-2075-4ceb-bd1a-e888697dffed"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Admis", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionId"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AdmissionId");

                    b.HasIndex("PatientID");

                    b.HasIndex("UserId");

                    b.ToTable("Admis");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Admission", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionId"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AdmissionId");

                    b.HasIndex("PatientID");

                    b.HasIndex("UserId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Allergy", b =>
                {
                    b.Property<int>("AllergyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergyID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("AllergyID");

                    b.HasIndex("PatientID");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Bed", b =>
                {
                    b.Property<int>("BedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BedID"));

                    b.Property<string>("AllocatedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit")
                        .HasColumnName("is_occupied");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BedID");

                    b.HasIndex("RoomID");

                    b.ToTable("Beds", (string)null);
                });

            modelBuilder.Entity("VirtualHealthProject.Models.BedAllocation", b =>
                {
                    b.Property<int>("AllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationID"));

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BedID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllocationID");

                    b.HasIndex("BedID")
                        .IsUnique();

                    b.HasIndex("PatientID");

                    b.ToTable("BedAllocation", (string)null);
                });

            modelBuilder.Entity("VirtualHealthProject.Models.ChronicIllness", b =>
                {
                    b.Property<int>("ChronicIllnessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChronicIllnessID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("ChronicIllnessID");

                    b.HasIndex("PatientID");

                    b.ToTable("ChronicIllnesses");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.ConsumableStockLevels", b =>
                {
                    b.Property<int>("ConsumableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumableId"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.HasKey("ConsumableId");

                    b.ToTable("ConsumableStockLevels");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.CurrentMedication", b =>
                {
                    b.Property<int>("CurrentMedicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrentMedicationID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("CurrentMedicationID");

                    b.HasIndex("PatientID");

                    b.ToTable("CurrentMedications");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Discharge", b =>
                {
                    b.Property<int>("DischargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DischargeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DischargeDate")
                        .HasColumnType("date");

                    b.Property<string>("DischargeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DischargeId");

                    b.HasIndex("PatientID");

                    b.HasIndex("UserId");

                    b.ToTable("Discharges");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.DispenceMedication", b =>
                {
                    b.Property<int>("DispenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispenceId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("DispenceId");

                    b.ToTable("DispenceMedication");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.DoctorVisit", b =>
                {
                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Instructions")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmitted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<bool>("Prescription")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduledMedication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasIndex("UserId");

                    b.ToTable("DoctorVisit");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.DoctorVisits", b =>
                {
                    b.Property<int>("VisitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitsId"));

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitsId");

                    b.HasIndex("PatientID");

                    b.HasIndex("UserId");

                    b.ToTable("DoctorVisits");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.InventoryHistory", b =>
                {
                    b.Property<int>("InventoryHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryHistoryId"));

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryHistoryId");

                    b.ToTable("InventoryHistories");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalHistoryID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("MedicalHistoryID");

                    b.HasIndex("PatientID");

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.NurseDispense", b =>
                {
                    b.Property<int>("DispenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispenceId"));

                    b.Property<DateTime>("DatePrescribed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ScheduledMedication")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DispenceId");

                    b.ToTable("NurseDispense");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.NurseInstruction", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RemarkDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InstructionId");

                    b.HasIndex("PatientID");

                    b.HasIndex("UserId");

                    b.ToTable("NurseInstructions");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicIllness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentMedication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryConcern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.PatientMovement", b =>
                {
                    b.Property<int>("PatientMovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientMovementID"));

                    b.Property<string>("Movement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MovementTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientMovementID");

                    b.HasIndex("PatientID");

                    b.ToTable("PatientMovements");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Prescription", b =>
                {
                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dispense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Rf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.PrescriptionScript", b =>
                {
                    b.Property<int>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionID"));

                    b.Property<DateTime?>("DateDeliveredToWard")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateForwardedToPharmacy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateWritten")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("PatientID");

                    b.HasIndex("UserId");

                    b.ToTable("PrescriptionScripts");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.ReferralLetter", b =>
                {
                    b.Property<int>("ReferralID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentMedications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryConcern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReferralID");

                    b.ToTable("ReferralLetters");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.RequestConsumables", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsumableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestConsumables");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7f270bed-70c3-46c2-bd83-c47b73eb7e2d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b3e54e7e-b16b-4779-b057-27bffdb4ce9d",
                            Email = "admin@virtualhealthbridge.com",
                            EmailConfirmed = false,
                            FirstName = "Justin",
                            LastName = "Fourie",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@VIRTUALHEALTHBRIDGE.COM",
                            NormalizedUserName = "ADMIN@VIRTUALHEALTHBRIDGE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG/b32z1//9GJGSESsLZgRxxwghzzWshjbv5EP0XsIbBC+pa24UTz5Ud1UaFxZV4/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "be5e3386-dc0d-4965-9c3c-674a295f98dc",
                            TwoFactorEnabled = false,
                            UserName = "admin@virtualhealthbridge.com"
                        },
                        new
                        {
                            Id = "1a9554cf-747d-4afb-81c0-4114eb8f8733",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a09fd9db-89ec-4c90-a1cb-23b388fcb883",
                            Email = "wardAdmin@virtualhealthbridge.com",
                            EmailConfirmed = false,
                            FirstName = "Qulon",
                            LastName = "Forbes",
                            LockoutEnabled = false,
                            NormalizedEmail = "WARDADMIN@VIRTUALHEALTHBRIDGE.COM",
                            NormalizedUserName = "WARDADMIN@VIRTUALHEALTHBRIDGE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJMK906yU/6LmOad7vgO8QjLkyAm3ZGEx1GB/aVxEbsPt5m9U9p0e7AYAtNB6ICb2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "528700d3-2f54-4485-87f2-5865b56dc39b",
                            TwoFactorEnabled = false,
                            UserName = "wardAdmin@virtualhealthbridge.com"
                        },
                        new
                        {
                            Id = "15a39159-9060-4425-8c3e-ba218c4ca37d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2270a20d-0e0a-4c01-8702-22c38e309a4d",
                            Email = "pharmacist@virtualhealthbridge.com",
                            EmailConfirmed = false,
                            FirstName = "Sheldon",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "PHARMACIST@VIRTUALHEALTHBRIDGE.COM",
                            NormalizedUserName = "PHARMACIST@VIRTUALHEALTHBRIDGE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEETKsb2uElcBEOwoJr6g2Roll/iMuU6U25YXvAEjhvu5l6z0KEUUisb36tguqC+fYw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "32a712ef-f5db-4579-968f-229737af1fe2",
                            TwoFactorEnabled = false,
                            UserName = "pharmacist@virtualhealthbridge.com"
                        },
                        new
                        {
                            Id = "a2f48359-0469-43b0-8654-f61b9d1ab286",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a49fb4e-8f62-4579-8ea4-5a0243a61e58",
                            Email = "stockmanager@virtualhealthbridge.com",
                            EmailConfirmed = false,
                            FirstName = "Brendon",
                            LastName = "Scott",
                            LockoutEnabled = false,
                            NormalizedEmail = "STOCKMANAGER@VIRTUALHEALTHBRIDGE.COM",
                            NormalizedUserName = "STOCKMANAGER@VIRTUALHEALTHBRIDGE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMUYYi7wWlnDoP6yBIQ17jZsuPyRRSPib7etWbU07ozL5ruxNJ3NNDCizG0AxPwNhw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d2457ea8-c4b3-4b04-8a38-a706fa125f7f",
                            TwoFactorEnabled = false,
                            UserName = "stockmanager@virtualhealthbridge.com"
                        },
                        new
                        {
                            Id = "854428da-d335-45ef-a793-dced73bbff77",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7beb1e3c-4c47-46ac-872d-5d8d99120422",
                            Email = "SCRIPTMANAGER@VIRTUALHEALTHBRIDGE.COM",
                            EmailConfirmed = false,
                            FirstName = "Bongani",
                            LastName = "Kunene",
                            LockoutEnabled = false,
                            NormalizedEmail = "SCRIPTMANAGER@VIRTUALHEALTHBRIDGE.COM",
                            NormalizedUserName = "SCRIPTMANAGER@VIRTUALHEALTHBRIDGE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMXvaruuXfRqTfPYZQDkKVjpXFrSVfLFy4yJRIWaXV7qbyH0faTfcAus1vOUTDEzbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb6137fa-3247-4ac4-96cd-c433984a01f2",
                            TwoFactorEnabled = false,
                            UserName = "scriptmanager@virtualhealthbridge.com"
                        },
                        new
                        {
                            Id = "9668a0c8-1c05-4240-b413-18b4c4bf1873",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be8f49b2-b8ca-4ace-a156-6fd1febe72be",
                            Email = "NURSE@VIRTUALHEALTHBRIDGE.COM",
                            EmailConfirmed = false,
                            FirstName = "Juliet",
                            LastName = "Links",
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE@VIRTUALHEALTHBRIDGE.COM",
                            NormalizedUserName = "NURSE@VIRTUALHEALTHBRIDGE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPwQuWtCa+mqAZLjTjxDJkHEHajDZi+RTleyT4wMdcBZUTfFazInwKbcd7QB+OzohA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4529b04-3e17-4160-b3df-f7fe4f4a52ab",
                            TwoFactorEnabled = false,
                            UserName = "nurse@virtualhealthbridge.com"
                        },
                        new
                        {
                            Id = "c4e8abc4-dbbf-406d-8031-20509b79c1a4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af1d7da1-78d4-48c0-9882-adf196d827a9",
                            Email = "DOCTOR@VIRTUALHEALTHBRIDGE.COM",
                            EmailConfirmed = false,
                            FirstName = "Gregory",
                            LastName = "Pikk",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR@VIRTUALHEALTHBRIDGE.COM",
                            NormalizedUserName = "DOCTOR@VIRTUALHEALTHBRIDGE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECMoAvyGd9VLy9UuCMfn30kqnL2hdyFPgxIBeX2/XzMcSfvw3kVuF7VuovEi4HhvDg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e8b7121e-940e-45b5-b976-52aa3b9004e6",
                            TwoFactorEnabled = false,
                            UserName = "doctor@virtualhealthbridge.com"
                        });
                });

            modelBuilder.Entity("VirtualHealthProject.Models.ViewConsumablesStock", b =>
                {
                    b.Property<int>("ConsumableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumableId"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.HasKey("ConsumableId");

                    b.ToTable("viewConsumablesStocks");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Vitals", b =>
                {
                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PainLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PulseRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleMedication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VitalsId")
                        .HasColumnType("int");

                    b.Property<string>("scheduleIVMedications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scheduleVMedications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Vitals");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.WeeklyStockTakes", b =>
                {
                    b.Property<int>("StockTakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTakeID"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConsumableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockNeeded")
                        .HasColumnType("int");

                    b.HasKey("StockTakeID");

                    b.ToTable("WeeklyStockTakes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualHealthProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Admis", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualHealthProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Admission", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualHealthProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Allergy", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Bed", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.BedAllocation", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Bed", "Bed")
                        .WithOne("BedAllocation")
                        .HasForeignKey("VirtualHealthProject.Models.BedAllocation", "BedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.ChronicIllness", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany("ChronicIllnesses")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.CurrentMedication", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany("CurrentMedications")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Discharge", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualHealthProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.DoctorVisit", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.DoctorVisits", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patients")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualHealthProject.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Patients");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.MedicalHistory", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.NurseInstruction", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualHealthProject.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.PatientMovement", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.PrescriptionScript", b =>
                {
                    b.HasOne("VirtualHealthProject.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualHealthProject.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Bed", b =>
                {
                    b.Navigation("BedAllocation")
                        .IsRequired();
                });

            modelBuilder.Entity("VirtualHealthProject.Models.Patient", b =>
                {
                    b.Navigation("ChronicIllnesses");

                    b.Navigation("CurrentMedications");

                    b.Navigation("MedicalHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
